<?php
$form = $this->form;
$form->setAttribute('action', $this->url('lenta', array('action' => 'addLenta')))
    ->prepare();
echo $this->form()->openTag($form);


$text = $form->get('text');
$image = $form->get('image');

$itemNumber = 3;
for($n=0; $n<$itemNumber; $n++){
    $text->setName('text_'.$n);
    $image->setName('image_'.$n);
    echo $this->formRow($text);
    echo $this->formRow($image);
}

?>




<?php

echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?>