<?php
$users=$this->users;


?>
<div id="containerc">
    <table width="100%">
 <?php
    foreach($users as $us) {
 ?>
<tr>
    <td class="table_el" > <?php echo $this->gravatar($us['email']);?></td>
    <td class="table_el" ><?php echo $us['email']; ?> </td>
    <td class="table_el_d" ><a class="add_friend" href="<?php echo $this->url(
            'friends',
            array('action' => 'addFriend','id'=>$us['id'])
        );?>"></a></td>
    <td class="table_el_d" ><a class="delete_friend" href="<?php echo $this->url(
            'friends',
            array('action' => 'deleteFriend','id'=>$us['id'])
        );?>"></td>
</tr>
        <?php
        }
        ?>
        </table>
    </div>
</div>